---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
  - binary: kubectl-naglfar
    id: kubectl-naglfar
    main: ./cmd/kubectl-naglfar/
    goarch:
      - amd64
    goos:
      - linux
      - darwin

archives:
  - files:
    - none*
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'
