apiVersion: naglfar.pingcap.com/v1
kind: Machine
metadata:
  name: 172.16.0.1
  labels:
    type: physical
spec:
  username: root
  password: root
  host: 172.16.0.1

---

apiVersion: v1
kind: Namespace
metadata:
  name: test-tidb-cluster
---

apiVersion: naglfar.pingcap.com/v1
kind: TestResourceRequest
metadata:
  name: test-tidb-cluster
  namespace: test-tidb-cluster
spec:
  items:
    - name: n1
      spec:
        memory: 1000
        cpuPercent: 100
        disks:
          - name: disk1
            kind: nvme
            size: 10000000
            mountPath: "/disks1"
        testMachineResource: 172.16.0.1
    - name: n2
      spec:
        memory: 1073741824
        cpuPercent: 600
        machineSelector: physical
        disks:
          - name: data1
            kind: nvme


