
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-machine
  failurePolicy: Fail
  name: mmachine.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-testclustertopology
  failurePolicy: Fail
  name: mtestclustertopology.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testclustertopologies
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-testresource
  failurePolicy: Fail
  name: mtestresource.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testresources
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-testresourcerequest
  failurePolicy: Fail
  name: mtestresourcerequest.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testresourcerequests
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-naglfar-pingcap-com-v1-testworkload
  failurePolicy: Fail
  name: mtestworkload.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testworkloads

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-machine
  failurePolicy: Fail
  name: vmachine.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - machines
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-procchaos
  failurePolicy: Fail
  name: vprocchaos.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - procchaos
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-testclustertopology
  failurePolicy: Fail
  name: vtestclustertopology.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testclustertopologies
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-testresource
  failurePolicy: Fail
  name: vtestresource.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testresources
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-testresourcerequest
  failurePolicy: Fail
  name: vtestresourcerequest.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testresourcerequests
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-naglfar-pingcap-com-v1-testworkload
  failurePolicy: Fail
  name: vtestworkload.kb.io
  rules:
  - apiGroups:
    - naglfar.pingcap.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testworkloads
