apiVersion: naglfar.pingcap.com/v1
kind: Machine
metadata:
  name: 172.16.0.1
  labels:
    type: physical
spec:
  username: root
  password: root
  host: 172.16.0.1
  reserve:
    memory: 2GB
    cpuPercent: 200