apiVersion: v1
kind: Namespace
metadata:
  name: test-tidb-cluster
---

apiVersion: naglfar.pingcap.com/v1
kind: TestResourceRequest
metadata:
  name: test-tidb-cluster
  namespace: test-tidb-cluster
spec:
  machines:
    - name: 172.16.0.1
  items:
    - name: n1
      spec:
        memory: 1GB
        cores: 2
        disks:
          disk1:
            name: 
            kind: nvme
            size: 500GB
            mountPath: /disks1
        testMachineResource: 172.16.0.1
    - name: n2
      spec:
        memory: 10GB
        cores: 4
        disks:
          disk1:
            name: 
            kind: nvme
            size: 1TB
            mountPath: /disks1

