apiVersion: naglfar.pingcap.com/v1
kind: TestResourceRequest
metadata:
  name: test
  namespace: test
  labels:
    owner: naglfar
spec:
  items:
    - name: n1
      spec:
        memory: 1000
        cpuPercent: 100
        disks:
          - name: disk1
            kind: nvme
            size: 10000000
            mountPath: "/disks1"
        testMachineResource: 172.16.0.1
    - name: n2
      spec:
        memory: 1000
        cpuPercent: 100
        disks:
          - name: disk1
            kind: nvme
            size: 10000000
            mountPath: "/disks1"

