apiVersion: v1
kind: Namespace
metadata:
  name: test-tidb-cluster
---

apiVersion: naglfar.pingcap.com/v1
kind: TestResourceRequest
metadata:
  name: test-tidb-cluster
  namespace: test-tidb-cluster
spec:
  items:
    - name: n1
      spec:
        memory: 1GB
        cpuPercent: 200
        disks:
          disk1:
            name: 
            kind: nvme
            size: 500GB
            mountPath: /disks1
        testMachineResource: 172.16.0.1
    - name: n2
      spec:
        memory: 10GB
        cpuPercent: 400
        disks:
          disk1:
            name: 
            kind: nvme
            size: 1TB
            mountPath: /disks1

