apiVersion: naglfar.pingcap.com/v1
kind: TestClusterTopology
metadata:
  name: tct
  namespace: test
spec:
  resourceRequest: tr
  haProxy:
    control: n1
    version: latest
    mount:
      target: haproxy.cfg
      config: |-
        global   # 全局参数的设置
             user haproxy
             group haproxy
             daemon
             nbproc 16
             maxconn 4096

        defaults
             mode http
             retries 3
             option httplog
             option redispatch
             option abortonclose
             option dontlognull
             option httpclose
             contimeout 5000
             clitimeout 3000
             srvtimeout 3000

        listen status
             bind 0.0.0.0:1080
             mode http
             log global

        frontend http_4000_in
             bind 0.0.0.0:4000
             mode http
             default_backend app

        backend app
             mode http
             balance source
             server tidb1 n1:4000 cookie 1 check inter 2000 rise 3 fall 3 weight 2
             server tidb2 n2:4000 cookie 2 check inter 2000 rise 3 fall 3 weight 1
             server tidb3 n3:4000 cookie 3 check inter 1500 rise 3 fall 3 backup

        backend static_server
             mode http
             option httpchk GET /test/index.html
             server tidb1 n1:4000 cookie 3 check inter 2000 rise 3 fall 3
