# permissions for end users to view procchaos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: procchaos-viewer-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - procchaos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - procchaos/status
  verbs:
  - get
