# permissions for end users to view relationships.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relationship-viewer-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - relationships
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - relationships/status
  verbs:
  - get
