# permissions for end users to edit relationships.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relationship-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - relationships
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - relationships/status
  verbs:
  - get
