
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testclustertopologies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testclustertopologies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresourcerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresourcerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkflows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads/status
  verbs:
  - get
  - patch
  - update
