# permissions to do viewer testworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testworkload-viewer-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads/status
  verbs:
  - get
