# permissions to do edit testworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testworkload-editor-role
rules:
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - naglfar.pingcap.com
  resources:
  - testworkloads/status
  verbs:
  - get
  - patch
  - update
