name: "workflow"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2

      - name: "format"
        run: make install-controller-gen && make fmt

      - name: "build"
        run: make install-controller-gen && make all
